#Add a todo 
POST http://localhost:3500/
content-type : application/json

{
    "name" : "Todo 2"
}

###Get All Todos 
GET http://localhost:3500/

###Update a Todo either name / completed
PUT http://localhost:3500/
content-type : application/json

{
    "id": "696f2b1c-6a0c-40d2-a953-17a6bb3197af",
    "newname" : "Todo 2 updated"
}